import type { Config } from 'tailwindcss'
import tailwindcssAnimate from 'tailwindcss-animate'

const config: Config = {
    darkMode: ['class'],
    content: [
        './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                md: '2rem',
                lg: '3rem',
            },
        },
        extend: {
            fontFamily: {
                sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
                display: ['var(--font-space-grotesk)', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'display-xl': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
                'display-lg': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
                'display-md': ['3rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
                'display-sm': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
            },
            colors: {
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    primary: 'var(--downriver-950)',
                    secondary: 'var(--san-juan-800)',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                brand: {
                    DEFAULT: 'var(--brand-600)',
                    50: 'var(--brand-50)',
                    100: 'var(--brand-100)',
                    200: 'var(--brand-200)',
                    300: 'var(--brand-300)',
                    400: 'var(--brand-400)',
                    500: 'var(--brand-500)',
                    600: 'var(--brand-600)',
                    700: 'var(--brand-700)',
                    800: 'var(--brand-800)',
                    900: 'var(--brand-900)',
                },
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                color: {
                    charcoal: 'var(--charcoal)',
                    cardWarm: 'var(--card-warm)',
                    fiord: 'var(--fiord-700)',
                    athensGray: 'var(--athens-gray-100)',
                    pickledBluewood: 'var(--pickled-bluewood-800)',
                    mercury: 'var(--mercury-200)',
                    mirage: 'var(--mirage-950)',
                    persianBlue: 'var(--persian-blue-700)',
                    mischka: 'var(--mischka-200)',
                    studio: 'var(--studio-600)',
                    resolver: 'var(--revolver-950)',
                    alto: 'var( --alto-200)',
                    storm: 'var( --storm-dust-600)',
                    magnolia: 'var( --magnolia-50)',
                    french: 'var( --french-lilac-400)',
                    blue: 'var(--blue-chalk-100)',
                    charlote: 'var(--charlotte-100)',
                    haiti: 'var(--haiti-950)',
                    scampi: 'var(--scampi-700)',
                    moon: 'var(--moon-raker-200)',
                    cblue: 'var(--chetwode-blue-500)',
                    wood: 'var(--woodsmoke-950)',
                    chalk: 'var(--blue-chalk-100)',
                    gallery: 'var(--gallery-100)',
                    purble: 'var(--purple-heart-700)',
                    wild: 'var(--wild-sand-100)',
                    boulder: 'var(--boulder-500)',
                    masala: 'var(--masala-700)',
                    masala2: 'var( --masala-600)',
                    woodsmoke2: 'var(--woodsmoke-800)',
                    woodsmoke: 'var(--woodsmoke-900)',
                    woodsmoke3: 'var(--woodsmoke-950)',
                    maverick: 'var(--maverick-400)',
                    grape: 'var( --grape-950)',
                    purbleh: 'var( --purple-heart-700)',
                    mauve: 'var( --mauve-300)',
                    mine: 'var(--mine-shaft-800)',
                    blue2: 'var(--blue-chalk-800)',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
        },
    },
    plugins: [tailwindcssAnimate],
}
export default config
